import os
import re
import glob
from dataclasses import dataclass
from typing import List, Optional


@dataclass
class EAResult:
    name: str
    total_profit: float = 0.0
    max_drawdown: float = 0.0
    profit_factor: float = 0.0
    total_trades: int = 0
    win_rate: float = 0.0
    report_exists: bool = False


def clean_num(s: str) -> float:
    if not s:
        return 0.0
    s = re.sub(r'[^\d.\-]', '', s)
    try:
        return float(s)
    except ValueError:
        return 0.0


def parse_html_report(file_path: str) -> EAResult:
    name = os.path.splitext(os.path.basename(file_path))[0]
    result = EAResult(name=name)

    content = ""
    for enc in ['utf-16-le', 'utf-16', 'utf-8', 'gbk']:
        try:
            with open(file_path, 'r', encoding=enc) as f:
                content = f.read()
            if content:
                break
        except Exception:
            continue

    if not content:
        return result

    result.report_exists = True

    patterns = {
        'total_profit': [
            r'Total Net Profit.*?<b>(.*?)</b>',
            r'总净利润.*?<b>(.*?)</b>',
            r'净利润.*?<b>(.*?)</b>',
        ],
        'max_drawdown': [
            r'Maximal Drawdown.*?<b>.*?(\d+\.\d+).*?%?</b>',
            r'最大回撤.*?<b>.*?(\d+\.\d+).*?%?</b>',
        ],
        'profit_factor': [
            r'Profit Factor.*?<b>(.*?)</b>',
            r'获利因子.*?<b>(.*?)</b>',
        ],
        'total_trades': [
            r'Total Trades.*?<b>(.*?)</b>',
            r'总交易.*?<b>(.*?)</b>',
            r'成交笔数.*?<b>(.*?)</b>',
        ],
        'win_rate': [
            r'Winning Trades.*?<b>.*?\((\d+\.\d+)%\)</b>',
            r'胜率.*?<b>.*?\((\d+\.\d+)%\)</b>',
        ],
    }

    for key, regexes in patterns.items():
        for reg in regexes:
            match = re.search(reg, content, re.DOTALL | re.IGNORECASE)
            if match:
                val = match.group(1)
                if key == 'total_profit':
                    result.total_profit = clean_num(val)
                elif key == 'max_drawdown':
                    result.max_drawdown = clean_num(val)
                elif key == 'profit_factor':
                    result.profit_factor = clean_num(val)
                elif key == 'total_trades':
                    result.total_trades = int(clean_num(val))
                elif key == 'win_rate':
                    result.win_rate = clean_num(val)
                break

    return result


def generate_html_report(results: List[EAResult], output_path: str) -> str:
    html = """<!DOCTYPE html><html><head><meta charset="utf-8">
<title>EA Backtest Ranking</title>
<style>
body { font-family: 'Microsoft YaHei', sans-serif; padding: 20px; background: #f5f5f5; }
.container { background: white; padding: 30px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); max-width: 1000px; margin: auto; }
h1 { text-align: center; color: #2c3e50; border-bottom: 2px solid #4CAF50; padding-bottom: 15px; }
table { width: 100%; border-collapse: collapse; margin-top: 25px; }
th, td { padding: 15px; border-bottom: 1px solid #eee; text-align: center; }
th { background: #4CAF50; color: white; font-weight: bold; }
tr:hover { background-color: #f9f9f9; }
.pos { color: #27ae60; font-weight: bold; }
.neg { color: #e74c3c; font-weight: bold; }
.rank-1 { background-color: #e8f5e9; border: 2px solid #4CAF50; }
</style></head><body><div class="container">
<h1>EA Backtest Ranking Report</h1>
<table>
<tr><th>Rank</th><th>Strategy</th><th>Net Profit ($)</th><th>Max Drawdown (%)</th><th>Profit Factor</th><th>Trades</th><th>Win Rate (%)</th></tr>"""

    for i, r in enumerate(results):
        rank = i + 1
        p_cls = "pos" if r.total_profit >= 0 else "neg"
        r_cls = "rank-1" if rank == 1 and r.total_profit > 0 else ""
        html += f"""<tr class='{r_cls}'>
            <td>{rank}</td>
            <td style='font-weight:bold;'>{r.name}</td>
            <td class='{p_cls}'>{r.total_profit:,.2f}</td>
            <td>{r.max_drawdown:.2f}%</td>
            <td>{r.profit_factor:.2f}</td>
            <td>{r.total_trades}</td>
            <td>{r.win_rate:.2f}%</td>
        </tr>"""

    html += "</table><div style='margin-top:20px; text-align:right; color:#7f8c8d; font-size:0.9em;'>Auto-generated by MT5 EA Tester</div></div></body></html>"

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    return output_path
